#!/bin/bash
# Uninstall all launchd agents for the Agentic Trading system
set -e
PLIST_DIR="$HOME/Library/LaunchAgents"

# New core plists (operational-reliability spec)
CORE_PLISTS=(
    com.agentic-trader.pipeline-0940
    com.agentic-trader.pipeline-1130
    com.agentic-trader.pipeline-1330
    com.agentic-trader.pipeline-1530
    com.agentic-trader.monitor
    com.agentic-trader.session-reset
)

# Legacy plists (generated by old install_scheduler.sh)
LEGACY_PLISTS=(
    com.agentictrading.pricepoller
    com.agentictrading.dailysweep
    com.agentictrading.fulldesk
    com.agentictrading.headlinescan
    com.agentictrading.asianote
    com.agentictrading.morningbrief
    com.agentictrading.postclosewrap
    com.agentictrading.coveragedigest
    com.agentictrading.weekahead
)

echo "=== Agentic Trading Scheduler Uninstaller ==="
echo ""

echo "Removing core plists..."
for plist in "${CORE_PLISTS[@]}"; do
    if [ -f "$PLIST_DIR/$plist.plist" ]; then
        launchctl unload "$PLIST_DIR/$plist.plist" 2>/dev/null || true
        rm "$PLIST_DIR/$plist.plist"
        echo "  Removed $plist"
    fi
done

echo ""
echo "Removing legacy plists (if any)..."
for plist in "${LEGACY_PLISTS[@]}"; do
    if [ -f "$PLIST_DIR/$plist.plist" ]; then
        launchctl unload "$PLIST_DIR/$plist.plist" 2>/dev/null || true
        rm "$PLIST_DIR/$plist.plist"
        echo "  Removed $plist"
    fi
done

echo ""
echo "All schedulers uninstalled."
echo "To verify: launchctl list | grep -E 'agentic-trader|agentictrading'"
